name: flutter_blue_plus_winrt
description: Windows implementation of the flutter_blue_plus plugin.
version: 0.0.20
publish_to: none
homepage: https://github.com/chan150/flutter_blue_plus_winrt

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface:
    git:
      url: https://github.com/notquiteog/flutter_blue_plus_platform_interface.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      windows:
        pluginClass: FlutterBluePlusPlugin
        dartPluginClass: FlutterBluePlusWinrt
